from __future__ import annotations

import os

MODEL_RETRIEVAL_FUNCTION_ID = 21002

SEARCH_DISTANCE_THRESHOLD = float(os.getenv("CORONA_SEARCH_DISTANCE_THRESHOLD", "1.0"))
SEARCH_MAX_WORKERS = 4
GENERATION_MAX_WORKERS = max(
    1,
    int(os.getenv(
        "CORONA_GENERATION_MAX_WORKERS",
        os.getenv("CORONA_HUNYUAN_MAX_CONCURRENCY", "3"),
    ) or "3"),
)
GENERATION_MAX_RETRIES = 2
GENERATION_RETRY_DELAY = 3.0
